// <auto-generated />
using System;
using Mapeamento.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mapeamento.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307060544_InitialCreateWith15Points")]
    partial class InitialCreateWith15Points
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mapeamento.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ESTADOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Acre",
                            Sigla = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Alagoas",
                            Sigla = "AL"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Amapá",
                            Sigla = "AP"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Amazonas",
                            Sigla = "AM"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Bahia",
                            Sigla = "BA"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Ceará",
                            Sigla = "CE"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Distrito Federal",
                            Sigla = "DF"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Espírito Santo",
                            Sigla = "ES"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Goiás",
                            Sigla = "GO"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Maranhão",
                            Sigla = "MA"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Mato Grosso",
                            Sigla = "MT"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Mato Grosso do Sul",
                            Sigla = "MS"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Minas Gerais",
                            Sigla = "MG"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Pará",
                            Sigla = "PA"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Paraíba",
                            Sigla = "PB"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Paraná",
                            Sigla = "PR"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "Pernambuco",
                            Sigla = "PE"
                        },
                        new
                        {
                            Id = 18,
                            Nome = "Piauí",
                            Sigla = "PI"
                        },
                        new
                        {
                            Id = 19,
                            Nome = "Rio de Janeiro",
                            Sigla = "RJ"
                        },
                        new
                        {
                            Id = 20,
                            Nome = "Rio Grande do Norte",
                            Sigla = "RN"
                        },
                        new
                        {
                            Id = 21,
                            Nome = "Rio Grande do Sul",
                            Sigla = "RS"
                        },
                        new
                        {
                            Id = 22,
                            Nome = "Rondônia",
                            Sigla = "RO"
                        },
                        new
                        {
                            Id = 23,
                            Nome = "Roraima",
                            Sigla = "RR"
                        },
                        new
                        {
                            Id = 24,
                            Nome = "Santa Catarina",
                            Sigla = "SC"
                        },
                        new
                        {
                            Id = 25,
                            Nome = "São Paulo",
                            Sigla = "SP"
                        },
                        new
                        {
                            Id = 26,
                            Nome = "Sergipe",
                            Sigla = "SE"
                        },
                        new
                        {
                            Id = 27,
                            Nome = "Tocantins",
                            Sigla = "TO"
                        });
                });

            modelBuilder.Entity("Mapeamento.Domain.Entities.PontoTuristico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("PONTOS_TURISTICOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cidade = "Rio de Janeiro",
                            DataCriacao = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Estátua icônica de Jesus Cristo, uma das maravilhas do mundo moderno.",
                            EstadoId = 19,
                            Localizacao = "Topo do Morro do Corcovado",
                            Nome = "Cristo Redentor",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Cidade = "São Paulo",
                            DataCriacao = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Principal centro financeiro e cultural de São Paulo, com museus e eventos.",
                            EstadoId = 25,
                            Localizacao = "Região Central da cidade",
                            Nome = "Avenida Paulista",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Cidade = "Santana do Riacho",
                            DataCriacao = new DateTime(2024, 1, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Parque Nacional com cachoeiras, trilhas e biodiversidade exuberante.",
                            EstadoId = 13,
                            Localizacao = "MG-010, Serra do Cipó",
                            Nome = "Serra do Cipó",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            Cidade = "Salvador",
                            DataCriacao = new DateTime(2024, 1, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Centro histórico de Salvador com arquitetura colonial preservada.",
                            EstadoId = 5,
                            Localizacao = "Centro Histórico",
                            Nome = "Pelourinho",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            Cidade = "Corumbá",
                            DataCriacao = new DateTime(2024, 1, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Maior planície alagável do mundo com biodiversidade única.",
                            EstadoId = 12,
                            Localizacao = "Região Centro-Oeste",
                            Nome = "Pantanal",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            Cidade = "Foz do Iguaçu",
                            DataCriacao = new DateTime(2024, 1, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Conjunto de quedas d'água espetaculares na fronteira com Argentina.",
                            EstadoId = 16,
                            Localizacao = "Parque Nacional do Iguaçu",
                            Nome = "Cataratas do Iguaçu",
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            Cidade = "Manaus",
                            DataCriacao = new DateTime(2024, 1, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Casa de ópera histórica no coração da Amazônia.",
                            EstadoId = 4,
                            Localizacao = "Centro de Manaus",
                            Nome = "Teatro Amazonas",
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            Cidade = "Barreirinhas",
                            DataCriacao = new DateTime(2024, 1, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Parque nacional com dunas de areia branca e lagoas cristalinas.",
                            EstadoId = 10,
                            Localizacao = "Parque Nacional dos Lençóis Maranhenses",
                            Nome = "Lençóis Maranhenses",
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            Cidade = "Ouro Preto",
                            DataCriacao = new DateTime(2024, 1, 8, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cidade colonial com arquitetura barroca e história da mineração.",
                            EstadoId = 13,
                            Localizacao = "Centro da cidade",
                            Nome = "Centro Histórico de Ouro Preto",
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            Cidade = "Jericoacoara",
                            DataCriacao = new DateTime(2024, 1, 9, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Praia paradisíaca com dunas, lagoas e pôr do sol inesquecível.",
                            EstadoId = 6,
                            Localizacao = "Parque Nacional de Jericoacoara",
                            Nome = "Jericoacoara",
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            Cidade = "Fernando de Noronha",
                            DataCriacao = new DateTime(2024, 1, 10, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Arquipélago vulcânico com praias paradisíacas e vida marinha rica.",
                            EstadoId = 17,
                            Localizacao = "Arquipélago oceânico",
                            Nome = "Ilha de Fernando de Noronha",
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            Cidade = "Cambará do Sul",
                            DataCriacao = new DateTime(2024, 1, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cânions espetaculares com paisagens de tirar o fôlego.",
                            EstadoId = 21,
                            Localizacao = "Parque Nacional dos Aparados da Serra",
                            Nome = "Aparados da Serra",
                            Status = true
                        },
                        new
                        {
                            Id = 13,
                            Cidade = "Brasília",
                            DataCriacao = new DateTime(2024, 1, 12, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Capital federal com arquitetura modernista única no mundo.",
                            EstadoId = 7,
                            Localizacao = "Plano Piloto",
                            Nome = "Brasília",
                            Status = true
                        },
                        new
                        {
                            Id = 14,
                            Cidade = "Bonito",
                            DataCriacao = new DateTime(2024, 1, 13, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Destino de ecoturismo com rios cristalinos e cavernas impressionantes.",
                            EstadoId = 12,
                            Localizacao = "Região da Serra da Bodoquena",
                            Nome = "Bonito",
                            Status = true
                        },
                        new
                        {
                            Id = 15,
                            Cidade = "Balneário Camboriú",
                            DataCriacao = new DateTime(2024, 1, 14, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Praia urbana moderna com arranha-céus e vida noturna agitada.",
                            EstadoId = 24,
                            Localizacao = "Orla marítima",
                            Nome = "Balneário Camboriú",
                            Status = true
                        });
                });

            modelBuilder.Entity("Mapeamento.Domain.Entities.PontoTuristico", b =>
                {
                    b.HasOne("Mapeamento.Domain.Entities.Estado", "Estado")
                        .WithMany("PontosTuristicos")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("Mapeamento.Domain.Entities.Estado", b =>
                {
                    b.Navigation("PontosTuristicos");
                });
#pragma warning restore 612, 618
        }
    }
}
